import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
/*The alternative solution in this section: https://material.angular.io/guide/getting-started#step-3-import-the-component-modules */
import {
    MatAutocompleteModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatInputModule,
    MatRadioModule,
    MatSelectModule,
    MatMenuModule,
    MatCardModule,
    MatDividerModule,
    MatExpansionModule,
    MatListModule,
    MatStepperModule,
    MatTabsModule,
    MatTreeModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatBadgeModule,
    MatChipsModule,
    MatIconModule,
    MatSlideToggleModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatBottomSheetModule,
    MatDialogModule,
    MatSnackBarModule,
    MatPaginatorModule
} from '@angular/material';

@NgModule({
    imports: [
        BrowserAnimationsModule,
        MatAutocompleteModule,
        MatTooltipModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatFormFieldModule,
        MatInputModule,
        MatRadioModule,
        MatSelectModule,
        MatMenuModule,
        MatCardModule,
        MatDividerModule,
        MatExpansionModule,
        MatListModule,
        MatStepperModule,
        MatTabsModule,
        MatTreeModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatBadgeModule,
        MatChipsModule,
        MatIconModule,
        MatSlideToggleModule,
        /*  MatIconRegistry,*/
        MatProgressSpinnerModule,
        MatProgressBarModule,
        MatBottomSheetModule,
        MatDialogModule,
        MatSnackBarModule,
        MatPaginatorModule
    ],
    exports: [
        BrowserAnimationsModule,
        MatAutocompleteModule,
        MatTooltipModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatFormFieldModule,
        MatInputModule,
        MatRadioModule,
        MatSelectModule,
        MatMenuModule,
        MatCardModule,
        MatDividerModule,
        MatExpansionModule,
        MatListModule,
        MatStepperModule,
        MatTabsModule,
        MatTreeModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatBadgeModule,
        MatChipsModule,
        MatIconModule,
        MatSlideToggleModule,
        /*  MatIconRegistry,*/
        MatProgressSpinnerModule,
        MatProgressBarModule,
        MatBottomSheetModule,
        MatDialogModule,
        MatSnackBarModule,
        MatPaginatorModule
    ]
})
export class MaterialDesignModule { }

